# Generated by Django 3.2.11 on 2022-01-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=80)),
                ('angkatan', models.IntegerField()),
            ],
        ),
    ]
